name: Generate Coverage Badge

on:
  push:
    branches: [main]
  pull_request:

jobs:
  generate-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore and Test with Coverage
        run: |
          dotnet test --collect:"XPlat Code Coverage"
          reportgenerator -reports:"**/coverage.cobertura.xml" -targetdir:"coveragereport" -reporttypes:Badges

      - name: Commit coverage badge
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add coveragereport/badge_line.svg
          git commit -m "Update coverage badge"
          git push
