name: Generate Coverage Badge

on:
  push:
    branches:
      - main

jobs:
  coverage-badge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Install ReportGenerator
      run: dotnet tool install --global dotnet-reportgenerator-globaltool

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --configuration Debug --no-restore

    - name: Run tests with coverage
      run: dotnet test --collect:"XPlat Code Coverage"

    - name: Generate Coverage Report
      env:
        PATH: $PATH:/home/runner/.dotnet/tools
      run: reportgenerator -reports:**/coverage.cobertura.xml -targetdir:coverage-report -reporttypes:Html
